### ISSUE TITLE
Unknown JSON key: 'email'

### ISSUE THREAD

**Issue by martinburchell** [RudolfCardinal/camcops#137]
A user writes:

We have installed CAMCOPS on a new device and set it up for upload to our camcops server in full accordance with the settings on our two well-functioning devices.
We have now run the first test on the new device and tried to upload the data to the server. That results in an error from the server saying "Unknown JSON key: 'email'.
What do we need to do to fix that?

**Comment by martinburchell** [comment]
Likely incompatible client and server. Can we detect that and report this to the user?

**Comment by RudolfCardinal** [comment]
Two approaches come to mind: (1) accept but ignore unknown JSON keys -- but risk of data loss here if a new client adds something important (as in this case); (2) fix the minimum version required. (2A) If the problem were the server being to new, we'd increase ``MINIMUM_TABLET_VERSION_STRING`` in ``cc_version.py``. (2B) But here, the problem is the client being too new, which can be handled by increasing ``MINIMUM_SERVER_VERSION`` in ``camcopsversion.cpp``. In general we shouldn't do this lightly, but maybe this is one of those moments. (Tangentially related: at some point we could also clean up the Python upload code if we removed support for *very* old clients that had a fixed maximum number-of-ID-numbers, rather than the linked table approach used now.)

**Comment by martinburchell** [comment]
I was thinking (2) originally because the current error message doesn't explain what the problem is.

I think this would prevent the following though:

* User creates records on client app < 2.4.0
* User upgrades to client app >= 2.4.0
* User uploads records

As the code stands, this should work without error because the patients won't have been created with email addresses.
I suppose if the user sees an incompatibility error message they can always downgrade the client.

**Comment by RudolfCardinal** [comment]
Not sure if that will work -- the newer client will still send something like '"email": null' in the JSON, won't it? I was also thinking (2), on the basis that failure with an error is better than data loss. One thing I don't know how to address is whether it's possible to encourage users to clear off data before upgrading -- I can't think of a feasible way, except that in "single-patient" mode the data should be autocleared frequently.
