### ISSUE TITLE
Adding a task schedule to a patient again wipes previous entries

### ISSUE THREAD

**Issue by RudolfCardinal** [RudolfCardinal/camcops#218]
Steps to reproduce:
* Create Schedule 1
* Assign Schedule 1 to a test patient.
* Do things (e.g. submit a task).
* Edit the patient, click "Add task schedule", and add Schedule 1 again.

Result:
It looks happy at the time, but the completed tasks vanish, and the patient is offered the tasks again -- perhaps a new schedule item is being created and displacing the old? (The old tasks are still there, of course, but their completion isn't recognized.)

(Currently testing in fhir-dev branch with v2.4.12 -- not finished/fully committed yet, so hang on before inspecting? But noting here.)

**Comment by martinburchell** [comment]
@RudolfCardinal I can't imagine this is related to FHIR. Probably never tested. I'll take a look.

What's the expected behaviour here? I can see that it may be desirable for a patient to repeat a whole schedule after a certain interval so it makes sense not to prevent this.

The logic for matching completed tasks to the schedule is here:

https://github.com/RudolfCardinal/camcops/blob/850a506702b3cfb0ffd6d77fa59f39317295f03d/server/camcops_server/cc_modules/cc_taskschedule.py#L180
 
Do the time periods of your two schedules overlap/

**Comment by RudolfCardinal** [comment]
I'm not completely sure. I agree that repeating later seems sensible. So maybe refuse to add if the two overlap, or the first hasn't started? I think the start date is undefined at creation, so maybe the safest is that you can't start if there is an unfinished schedule of the same type? (That would prevent people queuing up duplicates of the same type, but I can't imagine that being particularly helpful. In extremis the user could just create Schedule 2 that was functionally identical to Schedule 1...)

**Comment by martinburchell** [comment]
>  In extremis the user could just create Schedule 2 that was functionally identical to Schedule 1...)

I actually told one of our users to do this, not realising it was possible to assign the same schedule twice to a patient

**Comment by RudolfCardinal** [comment]
(And yes, the first schedule was started/in progress when I re-added it.)
